// Builds the project list the site shows, from three sources:
//   1. src/data/projects.json   generated by `npm run sync` (never hand-edited)
//   2. src/data/overrides.json  my manual changes per repo name (always win)
//   3. content/projects/*.md    optional longer write-ups for project pages
//
// This file reads from disk, so it only runs on the server / at build time.

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { marked } from "marked";

import synced from "@/data/projects.json";
import overridesFile from "@/data/overrides.json";

export const GROUPS = ["C++", "Python", "Other"] as const;
export type Group = (typeof GROUPS)[number];

type SyncedRepo = {
  name: string;
  description: string;
  language: string | null;
  group: string;
  url: string;
  homepageUrl: string | null;
  topics: string[];
  pushedAt: string;
};

type Override = {
  hide?: boolean;
  title?: string;
  summary?: string;
  group?: Group;
  demo?: string | null;
  featured?: boolean;
  order?: number;
};

export type Project = {
  name: string; // the GitHub repo name
  slug: string; // used in /projects/<slug>
  title: string;
  summary: string; // may be empty when GitHub has no description
  language: string | null;
  group: Group;
  codeUrl: string;
  demoUrl: string | null;
  topics: string[];
  pushedAt: string;
  featured: boolean;
  order: number;
  image: string | null; // optional screenshot in public/projects/
};

const ROOT = process.cwd();
const IMAGE_EXTENSIONS = ["webp", "png", "jpg", "jpeg"];

// Keys that start with "_" are notes/examples in overrides.json, not repos.
const overrides = Object.fromEntries(
  Object.entries(overridesFile).filter(([key]) => !key.startsWith("_")),
) as Record<string, Override>;

function isGroup(value: unknown): value is Group {
  return GROUPS.includes(value as Group);
}

/** "Advanced-Account-Management-System" -> "Advanced Account Management System" */
function prettifyRepoName(name: string): string {
  return name.replace(/[-_]+/g, " ").trim();
}

function findImage(name: string): string | null {
  for (const ext of IMAGE_EXTENSIONS) {
    if (existsSync(join(ROOT, "public", "projects", `${name}.${ext}`))) {
      return `/projects/${name}.${ext}`;
    }
  }
  return null;
}

function toProject(repo: SyncedRepo): Project {
  const o = overrides[repo.name] ?? {};
  return {
    name: repo.name,
    slug: repo.name.toLowerCase(),
    title: o.title ?? prettifyRepoName(repo.name),
    summary: o.summary ?? repo.description,
    language: repo.language,
    group: isGroup(o.group) ? o.group : isGroup(repo.group) ? repo.group : "Other",
    codeUrl: repo.url,
    // `demo: null` in overrides removes a demo link; leaving it out keeps GitHub's.
    demoUrl: o.demo !== undefined ? o.demo : repo.homepageUrl,
    topics: repo.topics,
    pushedAt: repo.pushedAt,
    featured: o.featured ?? false,
    order: o.order ?? Number.MAX_SAFE_INTEGER,
    image: findImage(repo.name),
  };
}

/** Featured first, then by "order", then most recently pushed. */
function compareProjects(a: Project, b: Project): number {
  if (a.featured !== b.featured) return a.featured ? -1 : 1;
  if (a.order !== b.order) return a.order - b.order;
  return b.pushedAt.localeCompare(a.pushedAt);
}

/** All projects that should appear on the site, in display order. */
export function getProjects(): Project[] {
  return (synced as SyncedRepo[])
    .filter((repo) => overrides[repo.name]?.hide !== true)
    .map(toProject)
    .sort(compareProjects);
}

export function getProject(slug: string): Project | undefined {
  return getProjects().find((project) => project.slug === slug);
}

/** The optional Markdown write-up for a project, converted to HTML. */
export async function getWriteupHtml(project: Project): Promise<string | null> {
  const file = join(ROOT, "content", "projects", `${project.name}.md`);
  if (!existsSync(file)) return null;
  // The Markdown is my own content from this repo, so rendering it as HTML is safe.
  return marked.parse(readFileSync(file, "utf8"), { async: true });
}

/** Display label for a project's language, e.g. "C++" or "JavaScript". */
export function languageLabel(project: Project): string {
  return project.language ?? project.group;
}
