// Builds the project list the site shows, from these sources:
//   1. src/data/projects.json        generated by `npm run sync` (never hand-edited)
//   2. src/data/overrides.json       my manual changes per repo name (always win)
//   3. src/data/language-groups.json the grouping rules (tab order lives here)
//   4. content/projects/*.md         optional longer write-ups for project pages
//
// This file reads from disk, so it only runs on the server / at build time.

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { marked } from "marked";

import synced from "@/data/projects.json";
import overridesFile from "@/data/overrides.json";
import groupRules from "@/data/language-groups.json";
// The same grouping code the sync script uses, so the tab order is defined once.
import { createGrouping, formatShare } from "../../scripts/lib/grouping.mjs";

type LanguageShare = { name: string; share: number }; // share in % of the repo's code

type SyncedRepo = {
  name: string;
  description: string;
  group: string; // chosen automatically by the sync script
  languages: LanguageShare[];
  isFork: boolean;
  forkOf: string | null; // "owner/repo" of the original, for forks
  url: string;
  homepageUrl: string | null;
  topics: string[];
  pushedAt: string;
};

type Override = {
  hide?: boolean;
  include?: boolean; // forces a fork to be shown (read by the sync script)
  title?: string;
  summary?: string;
  group?: string;
  demo?: string | null;
  featured?: boolean;
  order?: number;
};

export type Project = {
  name: string; // the GitHub repo name
  slug: string; // used in /projects/<slug>
  title: string;
  summary: string; // may be empty when GitHub has no description
  group: string; // the tab it appears under
  languages: LanguageShare[]; // its top languages, largest first
  forkOf: string | null; // set when the repo is a fork: "owner/repo" of the original
  codeUrl: string;
  demoUrl: string | null;
  topics: string[];
  pushedAt: string;
  featured: boolean;
  order: number;
  image: string | null; // optional screenshot in public/projects/
};

const ROOT = process.cwd();
const IMAGE_EXTENSIONS = ["webp", "png", "jpg", "jpeg"];
// How many languages to show per project, and the smallest share worth showing.
const MAX_LANGUAGES = 3;
const MIN_LANGUAGE_SHARE = 1;

const { compareGroups } = createGrouping(groupRules);

// Keys that start with "_" are notes/examples in overrides.json, not repos.
const overrides = Object.fromEntries(
  Object.entries(overridesFile).filter(([key]) => !key.startsWith("_")),
) as Record<string, Override>;

/** "Advanced-Account-Management-System" -> "Advanced Account Management System" */
function prettifyRepoName(name: string): string {
  return name.replace(/[-_]+/g, " ").trim();
}

function findImage(name: string): string | null {
  for (const ext of IMAGE_EXTENSIONS) {
    if (existsSync(join(ROOT, "public", "projects", `${name}.${ext}`))) {
      return `/projects/${name}.${ext}`;
    }
  }
  return null;
}

function topLanguages(languages: LanguageShare[]): LanguageShare[] {
  const shown = languages.filter((l) => l.share >= MIN_LANGUAGE_SHARE).slice(0, MAX_LANGUAGES);
  // A repo made only of tiny shares still shows its largest language.
  return shown.length > 0 ? shown : languages.slice(0, 1);
}

// Which forks appear is decided by the sync script (only forks with commits
// of my own, or "include": true), so projects.json only contains those.
// "hide": true always wins.
function isVisible(repo: SyncedRepo): boolean {
  return (overrides[repo.name] ?? {}).hide !== true;
}

function toProject(repo: SyncedRepo): Project {
  const o = overrides[repo.name] ?? {};
  return {
    name: repo.name,
    slug: repo.name.toLowerCase(),
    title: o.title ?? prettifyRepoName(repo.name),
    summary: o.summary ?? repo.description,
    // A group set in overrides.json always wins over the automatic one.
    group: o.group?.trim() || repo.group,
    languages: topLanguages(repo.languages),
    forkOf: repo.isFork ? (repo.forkOf ?? "another repository") : null,
    codeUrl: repo.url,
    // `demo: null` in overrides removes a demo link; leaving it out keeps GitHub's.
    demoUrl: o.demo !== undefined ? o.demo : repo.homepageUrl,
    topics: repo.topics,
    pushedAt: repo.pushedAt,
    featured: o.featured ?? false,
    order: o.order ?? Number.MAX_SAFE_INTEGER,
    image: findImage(repo.name),
  };
}

/** Featured first, then by "order", then most recently pushed. */
function compareProjects(a: Project, b: Project): number {
  if (a.featured !== b.featured) return a.featured ? -1 : 1;
  if (a.order !== b.order) return a.order - b.order;
  return b.pushedAt.localeCompare(a.pushedAt);
}

/** All projects that should appear on the site, in display order. */
export function getProjects(): Project[] {
  return (synced as SyncedRepo[]).filter(isVisible).map(toProject).sort(compareProjects);
}

/**
 * The tabs: every group that has at least one project, in tab order
 * (C / C++, Python, Java, JavaScript / TypeScript, the rest A-Z, Other last).
 */
export function getGroups(projects: Project[]): string[] {
  return [...new Set(projects.map((p) => p.group))].sort(compareGroups);
}

export function getProject(slug: string): Project | undefined {
  return getProjects().find((project) => project.slug === slug);
}

/** The optional Markdown write-up for a project, converted to HTML. */
export async function getWriteupHtml(project: Project): Promise<string | null> {
  const file = join(ROOT, "content", "projects", `${project.name}.md`);
  if (!existsSync(file)) return null;
  // The Markdown is my own content from this repo, so rendering it as HTML is safe.
  return marked.parse(readFileSync(file, "utf8"), { async: true });
}

/** "TypeScript 53%" (shares under 1% show as "<1%"). */
export function formatLanguage(language: LanguageShare): string {
  return `${language.name} ${formatShare(language.share)}`;
}
